2022-02-25 20:52:39,648 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002AF0287D680>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 24, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2022-02-25 20:52:39,654 ERROR "GET /news/index/ HTTP/1.1" 500 95278 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 20:53:21,816 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002AF02AD3400>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 24, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2022-02-25 20:53:21,821 ERROR "GET /news/index/ HTTP/1.1" 500 95415 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-02-25 20:54:42,300 ERROR Internal Server Error: /news/index/ C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('index.html'), <traceback object at 0x000002AF02C098C0>)
Traceback (most recent call last):
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\D11-module-v1\news_app\newapp\views.py", line 24, in get
    return HttpResponse(render(request, 'index.html', context))
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2022-02-25 20:54:42,304 ERROR "GET /news/index/ HTTP/1.1" 500 94821 C:\PycharmProjects\D11-module-v1\venv\lib\site-packages\django\core\servers\basehttp.py None
